#!/usr/bin/env bash

# _activate-project: set up a perl project in the current directory
# Copyright (C) 2014  Sapphire Cat <https://github.com/sapphirecat>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# FILES AND DIRECTORIES:
#
# foo/
#   activate    [this file, renamed and executable]
#   bin/
#   lib/
# ~/lib/foo/    [optional]
#
# More info: https://github.com/sapphirecat/bin

set -e

cd "$(dirname "$0")"
APP=`pwd -P`
activate_lib_dir="$HOME/lib/`basename "$APP"`"

[ ! -d "$activate_lib_dir" ] || eval `perl "-Mlocal::lib=$activate_lib_dir"`

export PATH="$APP/bin:$PATH"
export PERL5LIB="$APP/lib${PERL5LIB:+:$PERL5LIB}"

cmdline=( "${SHELL:-bash}" )
if [ "x$1" = x ] ; then
	cmdline=( "$@" )
fi

unset APP activate_lib_dir
exec /usr/bin/env "${cmdline[@]}"
