#!/usr/bin/env perl

# perl_has: display installed state of listed perl modules
# Copyright (C) 2012  Sapphire Cat <https://github.com/sapphirecat>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

use strict;
use warnings;

my $ANSI = {
	ok =>  "\e[32m",
	fail => "\e[1;33m",
	reset => "\e[0m",
};

show_mod($_) foreach sort @ARGV;

sub show_mod {
	my ($mod) = @_;
	my $v = eval qq{require $mod; \$${mod}::VERSION || 'ok';};
	my $color;
	if ($v) {
		$color = $ANSI->{ok};
	} else {
		$color = $ANSI->{fail};
		$v = 'MISSING';
	}
	print "$color$mod: $v$ANSI->{reset}\n";
}

